### ISSUE TITLE
add "private collections you belong to" to the user dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1655]
We have a lot of new collections and users coming online, and one of them pointed out that it is really hard to find a private collection.  The transcribers have to create an account, and then follow a link in an email or copy and paste the URL in.

We'd like to add "private collections you belong to" to the user dashboard.

Please add a query for "private collections you are a collaborator on" to the list of collections that show up on this page:
https://fromthepage.com/dashboard/watchlist

**Comment by diegoviola** [comment]
Fixed-by https://github.com/benwbrum/fromthepage/pull/1595.

**Comment by saracarl** [comment]
@diegoviola can you pull this into development as well?  I just had another user ask about it, which makes 2 in less than a week.  Because of so many folks using FromThePage for staff working at home, they are creating and collaborating on a lot of private collections.  Staff can't find them because of this.

**Comment by diegoviola** [comment]
@saracarl I just pushed the changes to development.

**Comment by saracarl** [comment]
@diegoviola I realized last night that #1595 doesn't resolve this.  That issue resolved "co-owner" issues.  We also have "collaborators", who don't have owner privileges, but can see and work on private collections.  Those are the users in question here.  We need collaborators to be able to see the private collections they can work on in their dashboard.

**Comment by diegoviola** [comment]
@saracarl can you please try #1668 ? I'll add tests after you confirm this is working. Thanks.
