### ISSUE TITLE
Background long-running subject name updates

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4662]
Currently, there are two instance in which `article.title` may be renamed, causing a bulk update of transcription text in pages referencing the article:
* Actually renaming `article.title` via the subject Settings tab, which updates the wikilinks referring to the article to use the new canonical name.
* De-duplicating two articles, which updates the wikilinks within pages referencing the merged article, pointing to the target article's canonical name.
Both of these actions happen within the browser request life-cycle.  The problem is that if thousands of pages link to that article, the request may time out, leaving orphan references to the article.  This happened in the Wilford Woodruff Papers recently, where an article mentioned on 4000 pages was renamed, and only 1500 pages were updated.

We need to move the bulk page update into a background task.

**Comment by benwbrum** [comment]
Was this fixed by #4663 ?

**Comment by saracarl** [comment]
This is affecting Dartmouth, WWP, and CWRGM.  It is not resolved yet.

**Comment by benwbrum** [comment]
We're still running into this in production, even after deploying #4663.  I think that the next step is to pull one of the big collections down to attempt it locally.

**Comment by benwbrum** [comment]
From Lindsey at CWRGM:

> On tags that I have tried to combine and it didn’t work (some are marked to be deleted), do I attempt to combine them again? For example, all references to the Mississippi Circuit Court are supposed to be combined under the [[[Mississippi--Judiciary. Circuit Courts]]](https://fromthepage.com/cwrgm/cwrgm-rev2/article/32118791/edit) tag, which has been annotated and is in two Organizations' child categories. But the following tags did not combine with it properly:
> [Courts & Judicial Systems--Circuit Courts](https://fromthepage.com/cwrgm/cwrgm-rev2/article/32242354/edit)
> [TO_BE_DELETED:Mississippi--Judiciary. Circuit Courts](https://fromthepage.com/cwrgm/cwrgm-rev2/article/32240009/edit)
> [TO_BE_DELETED:Mississippi--Judiciary. Circuit Courts](https://fromthepage.com/cwrgm/cwrgm-rev2/article/70054/edit)
> 
> Do I try combining them again?
> 
> Also, is there a way for me to try and find and delete tags that I have previously deleted but keep popping up again from old documents every few days, like Secretaries or Clerks? I can’t give links to these examples, however, because I can’t see them in FTP right now but I suspect they are still there in documents.

**Comment by benwbrum** [comment]
An update from Jon of the WWP project:

I know we've had some issues with name changes (or merging) and I don't know if this is related. Sometimes a name will get updated, but it's not replaced in all of the documents where they are tagged and a document is still tagged with the old name. Is there any way to fix these automatically or how do you suggest we reconcile them? 

For example, Frank Cutler (https://fromthepage.com/woodruff/wilford-woodruff-papers-project/article/32109365), who was formerly known as Frank Atkinson Cutler. You can see in https://fromthepage.com/woodruff/wilford-woodruff-papers-project/letter-from-frank-cutler-10-may-1895-le-43850/transcribe/34974535 that it's still tagged with Frank Atkinson Cutler, even though we don't have a person with that name in our subjects list, and this page is showing up as tagged with Frank Cutler (https://fromthepage.com/woodruff/wilford-woodruff-papers-project/article/32109365)

<img width="1048" height="240" alt="Image" src="https://github.com/user-attachments/assets/b2a96ef6-7f19-4fbd-bb9e-d40e769ecc52" />

<img width="1134" height="172" alt="Image" src="https://github.com/user-attachments/assets/591ae14e-2007-42db-9e54-1efa82720168" />

Interestingly, page_0001 of this document does have Frank Cutler tagged and not Frank Atkinson Cutler.

**Comment by saracarl** [comment]
Closing...  I think this is fixed now.
